Repository space-metaverse/space-ui, pull requests merged in 2022-11, with the labels that each got.

#10 Move ImageInput asset into lib.
  package-lock.json
  package.json
  src/assets/avatar.png
  src/components/ImageInput/ImageInput.tsx
Labels: bug, enhancement

#14 refactor(image-input): add tag image to render element
  src/components/ImageInput/index.tsx
  src/components/ImageInput/styles.ts
  src/components/ImageInput/types.ts
Labels: bug, enhancement

#15 feat(button): adding new styles
  src/components/Button/styles.ts
  src/components/Button/types.ts
  src/stories/components/Button.stories.tsx
  src/stories/components/ImageInput.stories.tsx
Labels: enhancement

#16 New buttons styles, deps changes.
  package-lock.json
  package.json
  src/components/Button/styles.ts
  src/components/Button/types.ts
  src/components/ImageInput/index.tsx
  src/components/ImageInput/styles.ts
  src/components/ImageInput/types.ts
  src/stories/components/Button.stories.tsx
  src/stories/components/ImageInput.stories.tsx
Labels: bug, enhancement

#12 Phone input
  package-lock.json
  package.json
  src/assets/arrow.svg
  src/components/PhoneInput/PhoneInput.tsx
  src/stories/components/PhoneInput.stories.tsx
Labels: enhancement

#17 fix when only have 1 button
  src/components/Modal/index.tsx
  src/components/Modal/styles.ts
Labels: bug

#18 Try to fix dummy avatar broken
  src/assets/avatar.png
  src/components/ImageInput/index.tsx
Labels: bug

#22 refactor(phone-input): better performance and apply theme
  src/components/PhoneInput/PhoneInput.tsx
  src/components/PhoneInput/index.tsx
  src/components/PhoneInput/styles.ts
  src/index.ts
  src/stories/components/PhoneInput.stories.tsx
Labels: bug, enhancement

#21 feat(text-input): add message of error
  src/components/TextInput/index.tsx
  src/components/TextInput/styles.ts
  src/components/TextInput/types.ts
  src/stories/components/Checkbox.stories.tsx
  src/stories/components/TextInput.stories.tsx
  src/stories/components/Toggle.stories.tsx
Labels: bug, enhancement

#23 feat(components): drag and drop
  src/components/DragAndDrop/index.tsx
  src/components/DragAndDrop/styles.ts
  src/components/DragAndDrop/types.ts
  src/components/NumberInput/styles.ts
  src/components/TextInput/styles.ts
  src/components/Textarea/styles.ts
  src/index.ts
  src/stories/components/DragAndDrop.stories.tsx
Labels: enhancement

#24 0.4.0
  package-lock.json
  package.json
  src/components/DragAndDrop/index.tsx
  src/components/DragAndDrop/styles.ts
  src/components/DragAndDrop/types.ts
  src/components/NumberInput/styles.ts
  src/components/PhoneInput/PhoneInput.tsx
  src/components/PhoneInput/index.tsx
  src/components/PhoneInput/styles.ts
  src/components/TextInput/index.tsx
  src/components/TextInput/styles.ts
  src/components/TextInput/types.ts
  src/components/Textarea/styles.ts
  src/index.ts
  src/stories/components/Checkbox.stories.tsx
  src/stories/components/DragAndDrop.stories.tsx
  src/stories/components/PhoneInput.stories.tsx
  src/stories/components/TextInput.stories.tsx
  src/stories/components/Toggle.stories.tsx
Labels: enhancement

#25 PhoneInput style improvements
  src/components/PhoneInput/index.tsx
  src/components/PhoneInput/styles.ts
Labels: bug, enhancement

#27 feat(components): create pagination
  src/components/Pagination/index.tsx
  src/components/Pagination/styles.ts
  src/components/Pagination/types.ts
  src/components/Pagination/usePagination.ts
  src/index.ts
  src/stories/components/Pagination.stories.tsx
Labels: enhancement

#28 Modal clear event refactored
  src/components/Modal/index.tsx
Labels: bug

#26 feat(components): add topnav and sidenav
  .storybook/preview.tsx
  package-lock.json
  package.json
  src/components/PhoneInput/index.tsx
  src/components/PhoneInput/styles.ts
  src/components/SideNav/index.tsx
  src/components/SideNav/styles.ts
  src/components/SideNav/types.ts
  src/components/TopNav/index.tsx
  src/components/TopNav/logo.ts
  src/components/TopNav/styles.ts
  src/index.css
  src/index.ts
  src/stories/components/SideNav.stories.tsx
  src/stories/components/TopNav.stories.tsx
Labels: enhancement

#30 Change type to accept jsx element and strings
  src/components/Checkbox/styles.ts
  src/components/Checkbox/types.ts
Labels: bug, enhancement

#31 v0.5.0 - TopNav, SideNav, fixes.
  .storybook/preview.tsx
  README.md
  package-lock.json
  package.json
  src/components/Checkbox/styles.ts
  src/components/Checkbox/types.ts
  src/components/Modal/index.tsx
  src/components/Pagination/index.tsx
  src/components/Pagination/styles.ts
  src/components/Pagination/types.ts
  src/components/Pagination/usePagination.ts
  src/components/PhoneInput/index.tsx
  src/components/PhoneInput/styles.ts
  src/components/SideNav/index.tsx
  src/components/SideNav/styles.ts
  src/components/SideNav/types.ts
  src/components/TopNav/index.tsx
  src/components/TopNav/logo.ts
  src/components/TopNav/styles.ts
  src/index.css
  src/index.ts
  src/stories/components/Pagination.stories.tsx
  src/stories/components/SideNav.stories.tsx
  src/stories/components/TopNav.stories.tsx
Labels: bug, enhancement

#29 Refactor phoneinput to fix some bugs
  package-lock.json
  package.json
  src/components/PhoneInput/index.tsx
  src/components/PhoneInput/styles.ts
  src/index.css
  src/stories/components/PhoneInput.stories.tsx
Labels: bug

#33 fix checkbox flex problem
  src/components/Checkbox/index.tsx
Labels: bug

#32 fix(components): sidenav and topnav
  src/components/SideNav/styles.ts
  src/components/TopNav/index.tsx
  src/components/TopNav/styles.ts
  src/stories/components/TopNav.stories.tsx
Labels: bug, enhancement

#35 change span to div because span it's used to set color on check square
  src/components/Checkbox/index.tsx
Labels: bug

#36 feat(components): spinner
  src/components/Spinner.tsx
  src/index.ts
  src/stories/components/Spinner.stories.tsx
Labels: enhancement

#37 feat(table): responsive
  src/components/Table/index.tsx
  src/components/Table/styles.ts
  src/components/Tabs/types.ts
Labels: enhancement
